name: qt551 
version: '5.5' 
summary: Qt 5.5.1 full runtime stack content snap. 
description: |
  This snap is to be consumed by various Qt apps which uses Qt 5.5.1 .
  Qt provides C++ classes and QML types for rendering GUI.

grade: stable 
confinement: strict 

architectures:
  - build-on: amd64
    run-on: amd64

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

slots: 
  qt551:
    interface: content
    read: 
      - $SNAP
parts:
    qt:
      plugin: nil
      stage-packages:
           - libqt5sql5-sqlite
           - libqt5webkit5
           - libqt5x11extras5
           - libqt5waylandclient5
           - libqt5xml5
           - libqt5opengl5-gles
           - libdb5.3
      build-attributes: 
       - no-system-libraries
      after: [desktop-qt5]   

    cleanup:
       after: 
            - qt
       plugin: nil
       override-prime: |
          # Remove unneeded stage files to save space
          cd usr/share
          rm -rf apport bash-completion bug doc doc-base icons lintian man pam-configs pkgconfig themes upstart zsh
