name: qt551 
version: '5.5' 
summary: Qt 5.5.1 full runtime stack content snap. 
description: |
  This snap is to be consumed by various Qt apps which uses Qt 5.5.1 .
  Qt provides C++ classes and QML types for rendering GUI.
  OTHER DEPENDENCIES:
    - mpv
    - ffmpeg
    - python
    - socat
    - wget
    - coreutils

grade: stable 
confinement: strict 
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

slots: 
  qt551:
    interface: content
    read: 
      - /
parts:
  desktop-qt5:
     source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
     source-subdir: qt
     plugin: make
     make-parameters: ["FLAVOR=qt5"]
     build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
     stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libqt5sql5-sqlite
      - libqt5webkit5
      - libqt5x11extras5
      - libqt5waylandclient5
      - libqt5xml5
      - libdb5.3
      - libgdk-pixbuf2.0-0
      - libqt5svg5 
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
      - libglu1-mesa
      - libslang2
  ppa:
     plugin: nil
     override-pull: |
       apt install wget
       echo "deb http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu bionic main" >>  /etc/apt/sources.list
       wget -qO - http://ktechpit.com/USS/Olivia/snapcraft/mpv.key | apt-key add -
       apt update
  app-depes:
     plugin: nil
     after: [ppa,desktop-qt5]
     stage-packages:
           - mpv
           - ffmpeg
           - python
           - socat
           - wget
           - coreutils
           - pv
           - libtag1v5
  qt5-gtk-platform:
     plugin: nil
     stage-packages:
      - qt5-gtk-platformtheme
  cleanup:
     after: 
       - desktop-qt5
     plugin: nil
     override-prime: |
       # Remove unneeded stage files to save space
       cd usr/share
       rm -rf apport bash-completion bug doc doc-base icons themes lintian man pam-configs pkgconfig upstart zsh
